import Lean
import ThalesDsl
import ThalesEmit.Json

/-! IR → `TSyntax` → text. Every line of Lean code in the artifact is
built by quotation and printed by Lean's pretty-printer; the only strings
assembled by hand are comments and the fixed header. Shapes beyond this
slice — multi-statement bodies, comparison operators, istrue conclusions
— are refused with a message naming the gap, never approximated. -/

namespace ThalesEmit

open Lean

/-- Syntax is built unhygienically — the artifact is plain text, so the
identifiers must print exactly as a person would write them. -/
abbrev RenderM := ExceptT String Unhygienic

def RenderM.run {α : Type} (x : RenderM α) : Except String α :=
  Unhygienic.run (ExceptT.run x)

partial def numTerm (lit : String) : RenderM (TSyntax `term) := do
  if lit == "Infinity" then `(floatInf)
  else if lit.startsWith "-" then
    let inner ← numTerm (lit.drop 1).toString
    `(-$inner)
  else if lit.any (fun c => c == '.' || c == 'e') then
    pure ⟨Syntax.mkScientificLit lit⟩
  else
    pure ⟨Syntax.mkNumLit lit⟩

/-- A plain identifier. The IR's names come from TypeScript identifiers,
which are Lean-atomic; anything else (a module-qualified closure name)
waits for its slice. -/
def identTerm (name : String) : RenderM Ident := do
  unless name.length > 0 && name.front.isAlpha &&
      name.all (fun c => c.isAlphanum || c == '_') do
    throw s!"'{name}' is not an emittable identifier yet"
  return mkIdent (Name.mkSimple name)

/-- `coerced` names the Int-valued binder variables: a use inside an
obligation body crosses to the Float world as `Float.ofInt x`, the same
boundary the old pipeline's binders cross. -/
partial def exprToTerm (coerced : String → Bool) : JsExpr → RenderM (TSyntax `term)
  | .num lit => numTerm lit
  | .id name => do
    let x ← identTerm name
    if coerced name then `(Float.ofInt $x) else pure x
  | .binop op l r => do
    let lt ← exprToTerm coerced l
    let rt ← exprToTerm coerced r
    match op with
    | "+" => `($lt + $rt)
    | "-" => `($lt - $rt)
    | "*" => `($lt * $rt)
    | "/" => `($lt / $rt)
    | _ => throw s!"operator '{op}' is not in the emission slice yet"
  | .call callee args => do
    let f ← identTerm callee
    let argTerms ← args.mapM (exprToTerm coerced)
    if argTerms.isEmpty then pure f else `($f $argTerms*)

def intEndpointTerm (i : Int) : RenderM (TSyntax `term) := do
  let n : TSyntax `term := ⟨Syntax.mkNumLit (toString i.natAbs)⟩
  if i < 0 then `(-$n) else pure n

def fnCommand (f : EmitFn) : RenderM (TSyntax `command) := do
  let name ← identTerm f.name
  let params ← f.params.mapM identTerm
  match f.body with
  | #[.ret e] =>
    let body ← exprToTerm (fun _ => false) e
    `(def $name ($params* : JsNumber) : JsM JsNumber := do
        return $body)
  | _ => throw s!"'{f.name}': only single-return bodies are in the emission slice yet"

def obligationCommand (e : Emission) (o : Obligation) : RenderM (TSyntax `command) := do
  let file := Syntax.mkStrLit e.file
  let fn := Syntax.mkStrLit o.function
  let prop := Syntax.mkStrLit o.property
  match o.payload with
  | .bare => `(#thales_prove $file $fn $prop)
  | .structured binders conclusion =>
    let bound := binders.map (·.name)
    let coerced := fun n => bound.contains n
    let leaf ← match conclusion with
      | .eq l r => do
        let lt ← exprToTerm coerced l
        let rt ← exprToTerm coerced r
        `($lt = $rt)
      | .istrue _ =>
        throw s!"'{o.property}': istrue conclusions are not in the emission slice yet"
    let propTerm ← binders.foldrM (init := leaf) fun b acc => do
      let xi ← identTerm b.name
      `(ballIco $(← intEndpointTerm b.lo) $(← intEndpointTerm b.hi) fun $xi => $acc)
    `(#thales_prove $file $fn $prop := $propTerm:term)

/-- The artifact's fixed header: scaffolding, not code the printer owns.
`autoImplicit` is pinned off because artifacts run under lean's defaults,
where an unbound identifier would auto-bind instead of erroring. -/
def header (e : Emission) : String :=
  s!"-- generated by thales-emit from {e.file}\n" ++
  "import ThalesDsl\n\n" ++
  "open Js ThalesDsl\n\n" ++
  "set_option autoImplicit false"

def commentLines (text : String) : String :=
  String.intercalate "\n"
    ((text.splitOn "\n").map fun line =>
      if line.isEmpty then "--" else s!"-- {line}")

/-- `Unhygienic` still stamps its one macro scope on quotation-literal
identifiers, which the printer would flag with `✝`; the artifact is
plain text, so the scopes are erased before printing. -/
partial def unscope : Syntax → Syntax
  | .ident info rawVal val preresolved =>
    .ident info rawVal val.eraseMacroScopes preresolved
  | .node info kind args => .node info kind (args.map unscope)
  | s => s

/-- The full artifact text. Pretty-printing runs in `CoreM` against an
environment that imports `ThalesDsl`, which carries every syntax the
quotations build. -/
def renderEmission (e : Emission) : CoreM String := do
  let mut blocks : Array String := #[header e]
  for f in e.declarations do
    let cmd ← rendered (fnCommand f)
    blocks := blocks.push
      (commentLines f.source ++ "\n" ++ (← ppCommand cmd).pretty 100)
  for o in e.obligations do
    let cmd ← rendered (obligationCommand e o)
    blocks := blocks.push
      (s!"-- @ensures\{{o.property}} {o.formula}\n" ++ (← ppCommand cmd).pretty 100)
  return String.intercalate "\n\n" blocks.toList ++ "\n"
where
  rendered (x : RenderM (TSyntax `command)) : CoreM (TSyntax `command) := do
    match RenderM.run x with
    | .error msg => throwError msg
    | .ok cmd => pure cmd
  ppCommand (cmd : TSyntax `command) : CoreM Format :=
    PrettyPrinter.ppCommand ⟨unscope cmd.raw⟩

end ThalesEmit
