#!/usr/bin/env node
import { parseArgs } from "node:util";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { buildSpecs } from "../engines/pabst/src/build-spec.js";
import { generate } from "../engines/pabst/src/codegen.js";
import { runTests } from "../engines/pabst/src/run.js";
import { parseSeed, randomSeed } from "../engines/pabst/src/seed.js";
import { resolveFiles } from "../lemma/src/discover.js";
import { LemmaError } from "../lemma/src/errors.js";
import { qualifiedName } from "../lemma/src/qualified-name.js";
import {
  buildEnvelope,
  notTriedEnvelope,
  type PropertyIdentity,
} from "./envelope.js";

// The module runs from src/ under vitest and dist/src/ as a bin, so
// package.json sits a different number of levels up in each: walk.
function readVersion(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  while (!existsSync(path.join(dir, "package.json"))) {
    const parent = path.dirname(dir);
    if (parent === dir) throw new Error("package.json not found");
    dir = parent;
  }
  return JSON.parse(readFileSync(path.join(dir, "package.json"), "utf8"))
    .version as string;
}

const USAGE =
  "usage: lakatos <prove|refute|check> [--seed <n>] [files-or-globs...]";

const HELP = `${USAGE}

commands:
  prove   try to prove each annotation (not implemented yet)
  refute  generate property tests from @ensures annotations, run them, and
          print a JSON report to stdout
  check   prove and refute combined (not implemented yet)

when no files are given, lakatos discovers your sources: the files that
tsconfig.json would compile or, failing that, src/**. declaration files
(.d.ts) are skipped unless a pattern names them.

options:
  --seed <n>  reproduce a prior refute run's generation (echoed in the report)
  -h, --help  show this help`;

const COMMANDS = ["prove", "refute", "check"] as const;
type Command = (typeof COMMANDS)[number];

export function main(argv: string[] = process.argv.slice(2)): number {
  // parseArgs throws on unknown options and the like — usage errors, which
  // map to the documented exit-2 mode; anything else crashes loudly.
  let positionals: string[];
  let values: { seed?: string; help?: boolean };
  try {
    ({ positionals, values } = parseArgs({
      args: argv,
      allowPositionals: true,
      options: {
        seed: { type: "string" },
        help: { type: "boolean", short: "h" },
      },
    }));
  } catch (e) {
    if (
      e instanceof TypeError &&
      "code" in e &&
      typeof e.code === "string" &&
      e.code.startsWith("ERR_PARSE_ARGS_")
    ) {
      console.error(USAGE);
      return 2;
    }
    throw e;
  }
  if (values.help) {
    console.log(HELP);
    return 0;
  }
  const command = positionals[0];
  const patterns = positionals.slice(1);
  if (!COMMANDS.includes(command as Command)) {
    console.error(USAGE);
    return 2;
  }
  // User-facing errors below — a bad --seed, file resolution coming up
  // empty, a malformed tsconfig, compile errors — are LemmaErrors and map
  // to the documented exit-2 error mode; anything else is an internal bug
  // and crashes loudly.
  try {
    return command === "refute"
      ? refute(patterns, values.seed)
      : notTried(command as Command, patterns);
  } catch (e) {
    if (e instanceof LemmaError) {
      console.error(`error: ${e.message}`);
      return 2;
    }
    throw e;
  }
}

function resolve(patterns: string[]): string[] {
  const { files, source } = resolveFiles(patterns);
  if (source !== "arguments") {
    console.error(
      `lakatos: no files given; discovered ${files.length} file(s) via ${source}`,
    );
  }
  return files;
}

function refute(patterns: string[], seedArg: string | undefined): number {
  const seed = seedArg !== undefined ? parseSeed(seedArg) : randomSeed();
  const files = resolve(patterns);
  const startedAt = new Date().toISOString();
  const cwd = process.cwd();
  const version = readVersion();

  const results = generate(files, ".pabst", seed);
  const identities: PropertyIdentity[] = results.flatMap((r) =>
    r.properties.map((p) => ({ file: r.sourceFile, ...p })),
  );
  const generated = identities.length;
  console.error(
    `lakatos: generated ${generated} propert${generated === 1 ? "y" : "ies"} across ${results.length} file(s) into .pabst/`,
  );

  const meta = { version, startedAt, cwd, seed, generated };

  // Scope the run to the out-files generated by THIS invocation: .pabst/
  // accumulates mirrors from earlier runs, and running the whole directory
  // would re-execute them and mix their issues into this envelope. With
  // nothing generated there is nothing to run — and an empty file list
  // would tell vitest to run everything, so short-circuit instead.
  if (results.length === 0) {
    console.log(
      JSON.stringify(
        { ...meta, passed: 0, failed: 0, annotations: [] },
        null,
        2,
      ),
    );
    return 0;
  }

  const result = runTests(results.map((r) => r.outFile));

  // Unhealthy runs (vitest died before reporting, or the generated suite
  // failed to load) still honor the output contract: diagnostics on stderr,
  // a NotTried envelope on stdout — the annotations were generated but
  // never evaluated — and the documented exit 2, not vitest's raw status.
  if (result.kind !== "completed") {
    if (result.kind === "no-results") {
      process.stderr.write(result.stdout);
      process.stderr.write(result.stderr);
    } else {
      for (const m of result.messages) console.error(`error: ${m}`);
    }
    console.log(
      JSON.stringify(
        {
          ...meta,
          annotations: identities.map((i) => ({ ...i, szs: "NotTried" })),
        },
        null,
        2,
      ),
    );
    return 2;
  }

  const envelope = buildEnvelope(meta, result.json, identities);
  console.log(JSON.stringify(envelope, null, 2));
  return (envelope.failed ?? 0) > 0 ? 1 : 0;
}

function notTried(command: Command, patterns: string[]): number {
  const files = resolve(patterns);
  const startedAt = new Date().toISOString();
  const cwd = process.cwd();
  const version = readVersion();
  const identities: PropertyIdentity[] = files.flatMap((file) =>
    buildSpecs(file).map((s) => ({
      file,
      function: qualifiedName(s.functionName, s.className, s.isStatic),
      property: s.name,
    })),
  );
  console.error(`lakatos: ${command} is not implemented yet`);
  console.log(
    JSON.stringify(
      notTriedEnvelope(version, startedAt, cwd, identities),
      null,
      2,
    ),
  );
  return 1;
}

// npm installs the bin as a symlink (node_modules/.bin/lakatos -> this
// file). Node resolves the main module to its realpath, but argv[1] keeps
// the symlink path, so argv[1] must be realpath'd before comparing.
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href
) {
  process.exit(main());
}
