import Js.NormAttr
import Js.Runtime
import Js.Binders
import Js.Number.Basic
import Js.Number.Constants
import Js.Number.FloatOps
import Js.Number.FloatFacts
import Js.Number.FloatOpsFacts
import Js.Val
import Js.Norm
